#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 13 21:15:09 2019

@author: beninman2
"""

s = 'abcdefghijklmnopqrstuvwxyz' # s is the string from which we are trying
#identify the longest alphabetical substring
temp = s[0]
long = ''

for i in range(len(s)-1):
    if s[i+1] >= s[i]:
        temp += s[i+1]
        print(temp)
    else: 
        if len(temp) > len(long):
            long = temp
            temp = s[i+1]
        else:
            temp = s[i+1]
            
if len(temp) > len(long):
    long = temp
print('Longest substring in alphabetical order is: ' + long)
    
    
    